version: '3.9'

services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER_FILE: /run/secrets/db_user
      MB_DB_PASS_FILE: /run/secrets/db_password
      MB_DB_HOST: postgres
    restart: always
    networks:
      - metanet1
    depends_on:
      - postgres
    secrets:
      - db_password
      - db_user

  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: metabase
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    restart: always
    networks:
      - metanet1
    secrets:
      - db_password
      - db_user

networks:
  metanet1:
    driver: bridge

secrets:
   db_password:
     file: db_password.txt
   db_user:
     file: db_user.txt

volumes:
  postgres_volume:
