services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_DATABASE: GlobalDataset
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

